### ISSUE TITLE
Not too sure how to interpret the error and follow up

### ISSUE THREAD

**Issue by chenlomis** [hackathon-cli-recommendation/cli-recommendation#6]
Was trying to go through:
group create -> app service create -> webapp create

but encountered the following error:
![image](https://user-images.githubusercontent.com/30876406/105440723-f2a98380-5c1b-11eb-9b9f-962c25882815.png)

Not entirely sure what the error meant... does it mean sampleWebApp is an invalid name..(?) or...?
I couldn't resolve the error on the spot...

Oh.. and I don't recall deployment-container-image-name being a required parameter...

---
After I thought I had a fix, I tried az next again, but it's indicating that there's no recommendation...
![image](https://user-images.githubusercontent.com/30876406/105440834-2684a900-5c1c-11eb-8bb0-2cf2caf23724.png)

Am wondering if it's possible for us to replicate the list of recommendation right after user encounters an error

---
Also another extremely minor thing...
![image](https://user-images.githubusercontent.com/30876406/105440860-31d7d480-5c1c-11eb-9115-e3d1c6bae1f3.png)

Would it be possible to convert the verb from present simple to past tense? So that "create" becomes "created" ? 

Thank you!

**Comment by zhoxing-ms** [comment]
Hi @chenlomis 
> Not entirely sure what the error meant... does it mean sampleWebApp is an invalid name..(?) or...?

This exception seems to be an error in getting the information of the existing webapp, possibly because this app does not exist under the current subscription.
You can use `az webapp show --name MyWebapp --resource-group MyResourceGroup` to check whether the app exists in the current subscription

> Am wondering if it's possible for us to replicate the list of recommendation right after user encounters an error

Maybe we can consider giving the failed command the chance to try again? This is easier to implement, do you think this design is feasible?

> Would it be possible to convert the verb from present simple to past tense? So that "create" becomes "created" ?

Good catch! Unfortunately, at present, these prompts are all from the help information of command. It is very difficult to support the intelligent change of the voice of words.

**Comment by chenlomis** [comment]
>>This exception seems to be an error in getting the information of the existing webapp, possibly because this app does not exist under the current subscription.

Hmm this is actually the odd part. Because when the "webapp create" command checks for any existing webapp with the same input name and found that its non existent, then it should proceed with the actual webapp create. But instead the experience outputted an error indicating that the webapp doesn't exist... that doesn't make sense...

Followed your recommendation and tried with webapp show... it's also indicating that it doesn't exist
![image](https://user-images.githubusercontent.com/30876406/105618677-ee59a380-5d9e-11eb-97bd-10e9d8ba01c2.png)

Would you know whether it's an error from our side or from the service team side? I could open a separate issue to track it otherwise



>>Maybe we can consider giving the failed command the chance to try again? This is easier to implement, do you think this design is feasible?

That may work! I couldn't really visualize how it works though. Did you mean giving the failed parameter another chance ? Or the whole command?

Also.. if possible... could you help me better understand why it'd be harder to replicate the same list of commands....?

I was thinking the flow would be:
az next presents options ABCDE -> user selects B -> user encounters an error -> az next checks for error conditions such that when user tries az next again -> az next would present the same options ABCDE instead of showing "sorry no recommendations"

**Comment by zhoxing-ms** [comment]
Hi @chenlomis 
> Would you know whether it's an error from our side or from the service team side? I could open a separate issue to track it otherwise

Yes, this is the problem of the app service team, which may be the logic of their design

> That may work! I couldn't really visualize how it works though. Did you mean giving the failed parameter another chance ? Or the whole command?

What I mean is to retry the failed command. The specific effect is as follows:
![Screenshot 2021-01-25 111454](https://user-images.githubusercontent.com/16612065/105657680-ed8c5300-5eff-11eb-8a0b-9b7584a58b55.png)

> Also.. if possible... could you help me better understand why it'd be harder to replicate the same list of commands....?
az next presents options ABCDE -> user selects B -> user encounters an error -> az next checks for error conditions such that when user tries az next again -> az next would present the same options ABCDE instead of showing "sorry no recommendations"

Because we will leave local records for failed commands. When the user executes "az next" again, we can't determine whether he needs the recommendation of Solution type to solve the exception, or he needs to get the previous recommendation result again (that's what you call ABCDE)

**Comment by chenlomis** [comment]
Thanks Xing!

Based on your elaboration, I’m thinking we may be misaligned on part of the user flow


Given the latest improvement and effort towards the error output design, I’m wondering how much value we’d be truly adding if error recovery is also part of az next’s offering

Here’s why:

Suppose I run az webapp create and encountered an error. The recommendations to help me resolve the error should already be there as part of the error output. (in fact, it is there). So unless az next’s errors recs were drastically different, I don’t really foresee people going out of their way to type az next just to get the same (?) error recommendations.
![image](https://user-images.githubusercontent.com/30876406/105756786-ed8d5280-5f01-11eb-8fec-e0a65cf446c9.png)

I think it’s nice as pitch that error recovery could be an additional scenario/offering under az next, but in reality, folks wouldn't do that if they already get direct recommendations from the error output

So where I see az next could add the most value is to provide additional insights on what users could do next from a broader scenario perspective, which means --- az next shall provide recs based on the previous command’s motivation, rather than the commands’ completeness/correctness 

And to your point here: _“When the user executes "az next" again, we can't determine whether he needs the recommendation of Solution type to solve the exception, or he needs to get the previous recommendation result again"_

That's a fair point, and hence my proposal would be to eliminate the confusion by removing the error recommendation part, which means:
1)	If previous command resulted in an error, then the direct error output should’ve informed him/her how to resolve it. Which is the primary reason why we invested so much in error improvement, and we don't need to replicate/duplicate that in az next; and 
2)	We observed in our series of interview that people were confused with the messaging “Sorry there’s no recommendation” when they wanted to see the same list of previous recommendations


Have we synced with Catherine/Houk/Roshanak/Christopher on the error output improvement story? I worry slightly that we may be duplicating the error recommendation effort

**Comment by chenlomis** [comment]
To add to the above, we might be thinking: "well but people can't run any of the az next commands unless their previous command has been executed successfully"

That's also a fair point too, so perhaps we could indicate that in the list of az next recommendations if there's any interdependency

For example: in the case of az webapp create throwing an error and user followed up with az next after that, we will still show them the list of recs but with additional "warning" indicating that: "XYZ commands can't be completed unless you first create a webapp"  

What do we think?

**Comment by zhoxing-ms** [comment]
Hi @chenlomis 
> If previous command resulted in an error, then the direct error output should’ve informed him/her how to resolve it. Which is the primary reason why we invested so much in error improvement, and we don't need to replicate/duplicate that in az next

Yes, I agree. We will plan to integrate with `error handling` in the future, without requiring users to input `az next` to trigger the recommendation of Solution

However, I have another concern: when the user has selected a command to execute but execution fails, is he more willing to retry the failed command or to retrieve the recommended result from the previous step?
If the user just wants to retry the selected command, he needs to re-execute `az next` and select options, these steps are redundant for him~

Personally, I guess: if users have already selected the recommended item, they may not be willing to choose other options if they need to select again in the same scenario just because of the execution error (rather than the recommendation does not meet their requirements)

**Comment by chenlomis** [comment]
Hmm
Good point
From the number of people we'd spoken with, they'd all gone back to re-running az next and expecting it to output the same list of recommendations when they were failing at the param-interactive workflow

So you're right that the _rerun_aznext -> reselect option_ part is redundant. It could also very well be that if users were able to recover from the errors during the exp, then they wouldn't have a need to rerun az next

To me there are 2 possible scenario where someone would rerun az next:
1) when (s)he fails at the param input exp and can't get through the command, then (s)he'd run az next again to try again. We could argue that once we improve the error recovery during the param-interactive walkthrough, then users wouldn't need to do so

2) when (s)he wants to start all over. The user may have entered the right value for the params but it may not have been the one intended, so (s)he would like to start fresh by re-runing az next

So I guess we've reached a conclusion that az next wouldn't confuse regular rec vs. error rec and that it would still provide recs even when user encounters an error; now the remaining Q is whether we resurface all the option or only the option for which (s)he'd failed at...

**Comment by zhoxing-ms** [comment]
> So I guess we've reached a conclusion that az next wouldn't confuse regular rec vs. error rec and that it would still provide recs even when user encounters an error; now the remaining Q is whether we resurface all the option or only the option for which (s)he'd failed at...

Yes, I think so~
I personally think that most of the problems may can be solved by letting the user retry the failed command and giving the corresponding help information to guide him to enter correct parameters. This can reduce the steps of re-executing `az next` and re-selecting recommended items for users.
The specific effects are as follows:
![１](https://user-images.githubusercontent.com/16612065/105982186-ed43b180-60d1-11eb-864a-295d49895f7b.png)

What do you think of this?

**Comment by chenlomis** [comment]
Plan sounds good to me! Let's see how people respond 

As for a different case where the previous command before az next fails, like the below
![image](https://user-images.githubusercontent.com/30876406/106046173-c451fb00-6096-11eb-9a5c-4d30117a9747.png)

I suppose we will start showing recommendations..(?)

**Comment by zhoxing-ms** [comment]
This is because there is only one record for this error in our statistics. Therefore, we need to accumulate enough statistics of this error to make the next recommendation, otherwise we can't avoid the contingency of the next command.
![Screenshot 2021-01-28 110705](https://user-images.githubusercontent.com/16612065/106084579-8ff34300-6159-11eb-9c9a-0a6b154728cb.png)

**Comment by chenlomis** [comment]
Hmm not sure whether we're on the same page...
I wasn't referring to the error recommendations from az next
but rather the recommendations for next set of commands. I thought the conclusion earlier was that we will provide follow up recs (not error rec) even when the previous command throws an error... or have I misunderstood?

**Comment by chenlomis** [comment]
That's okay 
Let's close this issue for now :)
